

import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import "./globals.css";
import MainLayout from "@/components/shared/MainLayout/MainLayout";
import AuthProvider from './provider/AuthProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Insight Forge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Toaster position="top-center" />
          <MainLayout>{children}</MainLayout>
        </AuthProvider>
       
      </body>
    </html>
  );
}