import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer/footer'
import Review from '@/Components/Review'
import Navbar from '@/components/shared/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Insight Forge',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar children={children}>
        </Navbar>
        <Review></Review>
      <Footer></Footer>
        </body>
      
    
    </html>
  )
}
